#!/usr/bin/env bash

# Tested on upgrades from 6.1.0-37-amd64 (Debian 12) to 6.1.0-38-amd64 (Debian
# 12) to 6.12.41+deb13-amd64 (Debian 13).

# https://kernel-team.pages.debian.net/kernel-handbook/ch-common-tasks.html

# Build dependencies for a "linux" source package and kernel header
# files have to be installed:
#
# apt build-dep linux
# apt install linux-headers-amd64


set -e

[[ "$1" == "triggered" ]] || exit 0

tmp_dir=$(mktemp -d "/tmp/linux-source.XXXXXXXX")

cd "$tmp_dir"

apt-get source linux

cd linux-*


while IFS= read -r line; do
	# linux-image-amd64 is a meta-package which depends on
	# the latest Linux kernel.
	case "$line" in
		"  Depends: linux-image-"*)
			ver="${line#  Depends: linux-image-}"
	esac
done < <(apt-cache depends linux-image-amd64)


printf "\n\n"

# Tested on br_private.h from Linux versions 4.19.322, 5.4.284, 5.10.228,
# 5.15.169, 6.1.114, 6.6.58, 6.10.14, 6.11.5, 6.12-rc5 and 6.12.41.
patch net/bridge/br_private.h << 'EOF'
--- net/bridge/br_private.h~	2024-09-16 19:25:58.596921741 +0000
+++ net/bridge/br_private.h	2024-09-16 19:29:11.990404581 +0000
@@ -44,8 +44,11 @@
 	BR_GROUPFWD_LACP	= BIT(2),
 };
 
-#define BR_GROUPFWD_RESTRICTED (BR_GROUPFWD_STP | BR_GROUPFWD_MACPAUSE | \
-				BR_GROUPFWD_LACP)
+/* #define BR_GROUPFWD_RESTRICTED (BR_GROUPFWD_STP | BR_GROUPFWD_MACPAUSE | \
+ * 				BR_GROUPFWD_LACP)
+ */
+#define BR_GROUPFWD_RESTRICTED	0
+
 /* The Nearest Customer Bridge Group Address, 01-80-C2-00-00-[00,0B,0C,0D,0F] */
 #define BR_GROUPFWD_8021AD	0xB801u
 
EOF

printf "\n\n"

# Kernel configuration is provided by "linux-image-<ver>" package which
# is a dependency for "linux-image-amd64" package.
cp -v /boot/config-"$ver" .config

# Module.symvers is provided by "linux-headers-<ver>" package which
# is a dependency for "linux-headers-amd64" package.
cp -v /usr/src/linux-headers-"$ver"/Module.symvers .


printf "\n%s\n\n" "make olddefconfig"
make olddefconfig

# Omitting the debug information on Debian Trixie(6.12.41+deb13-amd64) with
# "scripts/config --disable DEBUG_INFO_DWARF_TOOLCHAIN_DEFAULT" causes module
# not to load, that is, "modprobe -v bridge" prints "ERROR: could not insert
# 'bridge': Exec format error" and dmesg shows "module: x86/modules: Invalid
# relocation target, existing value is nonzero for type 1, loc 000000005be9d908,
# val ffffffffc0ccf2c0" error. Leave the debug info in and remove it later
# with strip.
#printf "\n%s\n\n" "scripts/config --disable DEBUG_INFO_DWARF_TOOLCHAIN_DEFAULT"
#scripts/config --disable DEBUG_INFO_DWARF_TOOLCHAIN_DEFAULT

printf "\n%s\n\n" "make modules_prepare"
make modules_prepare

printf "\n%s\n\n" "make M=net/bridge"
make M=net/bridge

printf "\n%s\n\n" "strip --strip-debug net/bridge/bridge.ko"
strip --strip-debug net/bridge/bridge.ko

modules_dir="/usr/lib/modules/$ver/kernel/net/bridge"

for module_name in bridge.ko bridge.ko.xz bridge.ko.zst; do

	current_module="$modules_dir/$module_name"

	if [[ -f "$current_module" ]]; then

		mv -v "$current_module" "$current_module.$(date +%s).bak"

		case "$module_name" in

			# CONFIG_MODULE_COMPRESS_XZ is set
			"bridge.ko.xz")
				# Match the xz options from kernel scripts/Makefile.modinst.
				xz -v -k --check=crc32 --lzma2=dict=1MiB net/bridge/bridge.ko
			;;

			# CONFIG_MODULE_COMPRESS_ZSTD is set
			"bridge.ko.zst")
				zstd -v -k net/bridge/bridge.ko
			;;

		esac

		cp -v net/bridge/"$module_name" "$modules_dir"
		break

	fi

done
